const SUPABASE_URL='https://czekazhacqaamwecjthp.supabase.co';
const SUPABASE_KEY='sb_publishable_Z51W6iueiL_dmRdmZe6_JQ_WoSirGA3';
async function fetchProducts(){const r=await fetch(`${SUPABASE_URL}/rest/v1/elegance_public_products?select=*&status=in.(published,sold_out)&order=featured.desc,title.asc`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});if(!r.ok)throw new Error(await r.text());return r.json()}
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n||0));
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function card(p){const img=(p.images||[])[0]||'https://placehold.co/700x700/0a141c/8bdcff?text=elegance';return `<article class="card"><img src="${esc(img)}" alt="${esc(p.title)}"><div class="card-body"><h3>${esc(p.title)}</h3><div class="meta">${esc(p.brand)} ${esc(p.model)} · ${esc(p.category)}</div><div class="price">${money(p.effective_price||p.price)}</div><a class="btn" href="/product.html?slug=${encodeURIComponent(p.slug)}">Ver producto</a></div></article>`}
async function catalog(){const grid=document.getElementById('grid');if(!grid)return;const status=document.getElementById('status');try{const all=await fetchProducts();const render=q=>{const f=all.filter(p=>JSON.stringify(p).toLowerCase().includes(q.toLowerCase()));grid.innerHTML=f.map(card).join('')||'<div class="empty">Todavía no hay productos publicados.</div>';status.textContent=`${f.length} producto(s) publicado(s)`};render('');document.getElementById('q').addEventListener('input',e=>render(e.target.value));}catch(e){status.textContent='No fue posible cargar el catálogo.';grid.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function product(){const el=document.getElementById('product');if(!el)return;const slug=new URLSearchParams(location.search).get('slug');try{const all=await fetchProducts();const p=all.find(x=>x.slug===slug);if(!p){el.innerHTML='<div class="empty">Producto no encontrado.</div>';return}const img=(p.images||[])[0]||'https://placehold.co/900x900/0a141c/8bdcff?text=elegance';const share=location.href;el.innerHTML=`<div><img src="${esc(img)}"></div><div><div class="meta">${esc(p.category)} · ${esc(p.brand)}</div><h1>${esc(p.title)}</h1><p>${esc(p.description)}</p><div class="price">${money(p.effective_price||p.price)}</div><p>Tallas: ${(p.sizes||[]).map(esc).join(', ')||'Por confirmar'}</p><p>Colores: ${(p.colors||[]).map(esc).join(', ')||'Por confirmar'}</p><button class="btn" onclick="navigator.clipboard.writeText('${share.replace(/'/g,"\\'")}')">Copiar enlace</button> <a class="btn" target="_blank" href="https://wa.me/?text=${encodeURIComponent(p.title+' '+share)}">Compartir por WhatsApp</a></div>`}catch(e){el.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
catalog();product();
