from __future__ import annotations


def mobile_html() -> str:
    return r'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#02080c"><link rel="manifest" href="/mobile/manifest.webmanifest"><title>elegance móvil</title><style>
:root{color-scheme:dark;--ice:#65d9ff;--bg:#02080c;--card:#0a1620;--muted:#91a7b4}*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:radial-gradient(circle at 80% 0,#123345 0,transparent 35%),var(--bg);color:#fff;min-height:100vh}.wrap{max-width:760px;margin:auto;padding:22px}.logo{font-family:cursive;font-size:42px;color:var(--ice);text-align:center;margin:12px}.tag{text-align:center;color:var(--muted);margin-bottom:22px}.card{background:linear-gradient(145deg,#0d1d29dd,#071119ee);border:1px solid #247fa455;border-radius:24px;padding:20px;box-shadow:0 18px 45px #0008;margin-bottom:16px}.drop{border:1.5px dashed #65d9ff77;border-radius:20px;padding:30px 18px;text-align:center}.big{font-size:52px}.btn{width:100%;border:0;border-radius:15px;padding:16px;margin-top:12px;font-size:17px;font-weight:800;background:linear-gradient(135deg,#63dbff,#178fca);color:#001018}.btn:disabled{opacity:.45}.ghost{background:#10232e;color:#bceeff;border:1px solid #2b7797}.stats{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.stat{background:#08131b;border-radius:15px;padding:13px}.stat b{font-size:24px;color:var(--ice);display:block}.progress{height:10px;background:#071018;border-radius:99px;overflow:hidden;margin:15px 0}.bar{height:100%;width:0;background:linear-gradient(90deg,#19bdff,#73f0d0);transition:.25s}.small{font-size:13px;color:var(--muted)}input[type=file]{display:none}.list{max-height:230px;overflow:auto}.row{padding:10px 0;border-bottom:1px solid #ffffff10}.ok{color:#66efaa}.err{color:#ff8282}@media(max-width:520px){.wrap{padding:14px}.logo{font-size:36px}.stats{grid-template-columns:1fr 1fr}}
</style></head><body><div class="wrap"><div class="logo">elegance</div><div class="tag">La elegancia se lleva al nacer y permanece en tus pies.</div>
<div class="card"><h2>📥 Bandeja de entrada</h2><p class="small">Selecciona fotos desde WhatsApp, Galería o Archivos. La computadora seguirá procesando aunque cierres esta pantalla.</p><div class="drop"><div class="big">📱</div><h3 id="chosen">Sin imágenes seleccionadas</h3><label class="btn ghost" for="files">Seleccionar imágenes</label><input id="files" type="file" accept="image/*" multiple><button id="upload" class="btn" disabled>Subir a elegance</button></div></div>
<div class="card"><h3>Estado del lote</h3><div class="progress"><div class="bar" id="bar"></div></div><div class="stats"><div class="stat"><b id="received">0</b>recibidas</div><div class="stat"><b id="processed">0</b>procesadas</div><div class="stat"><b id="products">0</b>productos</div><div class="stat"><b id="duplicates">0</b>duplicados</div></div><p id="status" class="small">Listo para recibir imágenes.</p><div id="latest" class="list"></div></div>
<div class="card"><button class="btn ghost" onclick="location.href='/mobile/install'">Agregar elegance a pantalla de inicio</button></div></div>
<script>
if('serviceWorker' in navigator)navigator.serviceWorker.register('/mobile/sw.js').catch(()=>{});let selected=[],batch=null,poll=null;const $=id=>document.getElementById(id);$('files').onchange=e=>{selected=[...e.target.files];$('chosen').textContent=`${selected.length} imágenes seleccionadas`;$('upload').disabled=!selected.length};
async function createBatch(){let r=await fetch('/api/mobile/batches',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({device_name:navigator.userAgent.includes('Android')?'Samsung S26 Ultra':'Dispositivo móvil',total:selected.length})});if(!r.ok)throw Error(await r.text());return r.json()}
async function sendFile(file,index){let fd=new FormData();fd.append('file',file,file.name);let r=await fetch(`/api/mobile/batches/${batch.id}/files`,{method:'POST',body:fd});if(!r.ok)throw Error(await r.text());$('status').textContent=`Subiendo ${index+1} de ${selected.length}…`;}
$('upload').onclick=async()=>{try{$('upload').disabled=true;batch=await createBatch();for(let i=0;i<selected.length;i++){await sendFile(selected[i],i);$('bar').style.width=`${Math.round((i+1)/selected.length*35)}%`}startPoll();$('status').textContent='Carga terminada. La PC procesa en segundo plano.'}catch(e){$('status').textContent='Error: '+e;$('upload').disabled=false}}
function startPoll(){clearInterval(poll);poll=setInterval(check,1400);check()}
async function check(){if(!batch)return;let r=await fetch(`/api/mobile/batches/${batch.id}`);if(!r.ok)return;let d=await r.json();$('received').textContent=d.received;$('processed').textContent=d.processed;$('products').textContent=d.products;$('duplicates').textContent=d.duplicates;let total=Math.max(1,d.total);$('bar').style.width=`${35+Math.round(d.processed/total*65)}%`;$('status').textContent=d.status==='done'?'✅ Todo quedó respaldado y publicado. Ya puedes borrar las fotos del teléfono.':`Procesando en la computadora: ${d.processed}/${d.total}`;$('latest').innerHTML=(d.latest||[]).map(x=>`<div class="row ${x.status==='error'?'err':x.status==='done'?'ok':''}">${x.original_name} — ${x.status}${x.result?`<br><small>${x.result.title||''}</small>`:''}</div>`).join('');if(d.status==='done')clearInterval(poll)}
</script></body></html>'''


def install_html() -> str:
    return """<!doctype html><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font-family:system-ui;background:#02080c;color:white;padding:28px;line-height:1.5}b{color:#65d9ff}</style><h1>Instalar elegance</h1><p>En Samsung Internet o Chrome abre el menú <b>⋮</b> y elige <b>Agregar a pantalla de inicio</b> o <b>Instalar aplicación</b>.</p><p>Después tendrás un ícono de elegance en tu S26.</p><a style='color:#65d9ff' href='/mobile'>Volver</a>"""
